name: dartfix
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description:
  A tool for migrating Dart source to newer versions of the Dart SDK,
  and fixing common issues.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  analysis_server_client: ^2.0.0
  args: any
  cli_util: any
  path: any
dev_dependencies:
  analyzer: ^0.33.0
  test: ^1.3.0
